[build]
  command = "pnpm build"
  publish = "dist"

# Basic redirect all requests to /index.html (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers example (CSP, etc.)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; script-src 'self'; connect-src 'self' wss:; style-src 'self' 'unsafe-inline'; img-src 'self' data:; media-src 'self'; frame-src 'self';"
