
---

# GitHub Workflows

### `.github/workflows/ci.yml`
```yaml
name: CI

on:
  push:
    branches: [ "main", "dev", "feature/*" ]
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install deps
        run: pnpm install
      - name: Lint
        run: npx eslint . --ext .ts,.tsx
      - name: Unit tests
        run: pnpm test
      - name: Hardhat tests
        run: |
          cd contracts
          pnpm install
          npx hardhat test
